# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: h2_sequence.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import h2_frame_grammar_pb2 as h2__frame__grammar__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='h2_sequence.proto',
  package='h2proto',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11h2_sequence.proto\x12\x07h2proto\x1a\x16h2_frame_grammar.proto\"*\n\x08Sequence\x12\x1e\n\x06\x66rames\x18\x01 \x03(\x0b\x32\x0e.h2proto.Frame\"e\n\x08\x45xchange\x12+\n\x10request_sequence\x18\x01 \x02(\x0b\x32\x11.h2proto.Sequence\x12,\n\x11response_sequence\x18\x02 \x02(\x0b\x32\x11.h2proto.Sequence\"4\n\x0c\x43onversation\x12$\n\texchanges\x18\x01 \x03(\x0b\x32\x11.h2proto.Exchange'
  ,
  dependencies=[h2__frame__grammar__pb2.DESCRIPTOR,])




_SEQUENCE = _descriptor.Descriptor(
  name='Sequence',
  full_name='h2proto.Sequence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='frames', full_name='h2proto.Sequence.frames', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=96,
)


_EXCHANGE = _descriptor.Descriptor(
  name='Exchange',
  full_name='h2proto.Exchange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_sequence', full_name='h2proto.Exchange.request_sequence', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='response_sequence', full_name='h2proto.Exchange.response_sequence', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=199,
)


_CONVERSATION = _descriptor.Descriptor(
  name='Conversation',
  full_name='h2proto.Conversation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='exchanges', full_name='h2proto.Conversation.exchanges', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=253,
)

_SEQUENCE.fields_by_name['frames'].message_type = h2__frame__grammar__pb2._FRAME
_EXCHANGE.fields_by_name['request_sequence'].message_type = _SEQUENCE
_EXCHANGE.fields_by_name['response_sequence'].message_type = _SEQUENCE
_CONVERSATION.fields_by_name['exchanges'].message_type = _EXCHANGE
DESCRIPTOR.message_types_by_name['Sequence'] = _SEQUENCE
DESCRIPTOR.message_types_by_name['Exchange'] = _EXCHANGE
DESCRIPTOR.message_types_by_name['Conversation'] = _CONVERSATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Sequence = _reflection.GeneratedProtocolMessageType('Sequence', (_message.Message,), {
  'DESCRIPTOR' : _SEQUENCE,
  '__module__' : 'h2_sequence_pb2'
  # @@protoc_insertion_point(class_scope:h2proto.Sequence)
  })
_sym_db.RegisterMessage(Sequence)

Exchange = _reflection.GeneratedProtocolMessageType('Exchange', (_message.Message,), {
  'DESCRIPTOR' : _EXCHANGE,
  '__module__' : 'h2_sequence_pb2'
  # @@protoc_insertion_point(class_scope:h2proto.Exchange)
  })
_sym_db.RegisterMessage(Exchange)

Conversation = _reflection.GeneratedProtocolMessageType('Conversation', (_message.Message,), {
  'DESCRIPTOR' : _CONVERSATION,
  '__module__' : 'h2_sequence_pb2'
  # @@protoc_insertion_point(class_scope:h2proto.Conversation)
  })
_sym_db.RegisterMessage(Conversation)


# @@protoc_insertion_point(module_scope)
